#!/usr/bin/env bash
# FinalRound local package — first-run setup.
#
# Checks prerequisites, generates backend/.env with a fresh JWT secret, starts
# the self-contained stack (docker-compose.local.yml), and seeds the coding-
# problem bank. Idempotent: safe to re-run any time.
#
# Usage:
#   ./setup_local.sh           # auto-detect engine (NVIDIA->vLLM, Apple Silicon->Ollama, else Gemini)
#   ./setup_local.sh --gpu     # force local Qwen via vLLM (needs NVIDIA GPU, ~10 GB VRAM)
#   ./setup_local.sh --ollama  # force local Qwen via native Ollama on macOS (Metal)
#   ./setup_local.sh --api     # force Gemini API mode (no GPU; bring your own key)
#
# Local inference is GPU-only: NVIDIA via vLLM, or Apple Silicon via Metal.
# There is no CPU path — see scripts/detect_engine.sh for why.
set -euo pipefail

cd "$(dirname "$0")"
COMPOSE="docker compose -f docker-compose.local.yml"

# MODE mirrors the inference engine: vllm | ollama | gemini.
MODE=""
for arg in "$@"; do
  case "$arg" in
    --gpu) MODE=vllm ;;
    --ollama) MODE=ollama ;;
    --api) MODE=gemini ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown option: $arg (try --help)"; exit 1 ;;
  esac
done

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is required. Install it from https://docs.docker.com/get-docker/"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: Docker Compose v2 is required (the 'docker compose' command)."
  exit 1
fi

# ── 2. Pick the inference engine ─────────────────────────────────────────────
# detect_engine.sh inspects OS/GPU/RAM and emits the engine + the backend env
# (VLLM_BASE_URL/VLLM_MODEL/VLLM_BASE_MODEL/AI_BACKEND). We point it at the
# compose service names so the URLs resolve on the compose network.
DETECT="scripts/detect_engine.sh"
DETECT_ARGS=(--explain)
[ -n "$MODE" ] && DETECT_ARGS=(--engine "$MODE" --explain)
ENGINE_ENV="$(PREPAI_VLLM_URL=http://vllm:8001/v1 \
              "$DETECT" "${DETECT_ARGS[@]}" 2>/dev/null)"
# shellcheck disable=SC2046
export $(echo "$ENGINE_ENV" | xargs)
MODE="$INFERENCE_ENGINE"
case "$MODE" in
  vllm)   echo "Engine: vLLM (NVIDIA GPU). Override with --ollama or --api." ;;
  ollama) echo "Engine: Ollama (Mac/AMD/CPU). Override with --gpu or --api." ;;
  gemini) echo "Engine: Gemini API (no local model). Override with --gpu/--ollama." ;;
  *) echo "ERROR: engine detection failed."; exit 1 ;;
esac

# ── 3. Generate backend/.env on first run ────────────────────────────────────
ENV_FILE=backend/.env
if [ ! -f "$ENV_FILE" ]; then
  if command -v openssl >/dev/null 2>&1; then
    SECRET=$(openssl rand -hex 64)
  else
    SECRET=$(head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')
  fi
  cat > "$ENV_FILE" <<EOF
# Generated by setup_local.sh — per-machine settings, never commit this file.
DB_NAME=FinalRound
JWT_SECRET=$SECRET

# Only used in Gemini API mode (no GPU). Get a free key: https://aistudio.google.com
GEMINI_API_KEY=
EOF
  echo "Wrote $ENV_FILE with a fresh JWT secret."
fi

if [ "$MODE" = "gemini" ] && ! grep -q '^GEMINI_API_KEY=..*' "$ENV_FILE"; then
  echo
  echo "NOTE: Gemini API mode needs a key. Either:"
  echo "  - add it to $ENV_FILE (GEMINI_API_KEY=...) and re-run this script, or"
  echo "  - paste it in the browser when the interview page asks for one."
  echo
fi

# ── 4. Start the stack ───────────────────────────────────────────────────────
# detect_engine.sh exported AI_BACKEND / VLLM_BASE_URL / VLLM_MODEL /
# VLLM_BASE_MODEL — compose interpolates them into the backend service.
case "$MODE" in
  vllm)
    # Prefer an adapter already on disk (the training box) over re-downloading
    # the identical weights from the Hub. Falls through to the compose default
    # (FinalRound/prepai-interviewer) on a fresh clone, where this dir is absent
    # because training/artifacts/ is gitignored.
    LOCAL_ADAPTER="training/artifacts/qwen2.5-7b-chatml-qlora-v2"
    if [ -f "$LOCAL_ADAPTER/adapter_model.safetensors" ]; then
      export INTERVIEWER_ADAPTER="/adapters/qwen2.5-7b-chatml-qlora-v2"
      export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
      echo "Interviewer adapter: local ($LOCAL_ADAPTER)"
    else
      echo "Interviewer adapter: FinalRound/prepai-interviewer (downloads once, ~646 MB)"
    fi
    echo "Starting FinalRound with the local Qwen model via vLLM."
    echo "(first run downloads ~5.5 GB of model weights into the hf-cache volume)"
    $COMPOSE --profile gpu up -d --build
    ;;
  ollama)
    # Ollama runs natively on the host so it can reach Metal — inside Docker on
    # a Mac it would silently decode on CPU. So we require the host daemon here
    # instead of starting the (GPU-less) ollama compose profile.
    if ! command -v ollama >/dev/null 2>&1; then
      echo "ERROR: Ollama must be installed natively on macOS (not in Docker)."
      echo "  brew install ollama   (or download from https://ollama.com/download)"
      echo "Then start it with:  ollama serve"
      exit 1
    fi
    if ! curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
      echo "ERROR: Ollama is installed but not running. Start it with: ollama serve"
      exit 1
    fi
    # Fetch the published interviewer adapter (~323 MB) unless it's already here.
    # The base is the stock public qwen2.5:7b-instruct tag, which `ollama create`
    # pulls on demand — we never host a copy of an unmodified public model.
    ADAPTER_GGUF="ollama/models/interviewer-lora.gguf"
    if [ ! -f "$ADAPTER_GGUF" ]; then
      echo "Downloading the interviewer adapter (~323 MB)..."
      mkdir -p ollama/models
      curl -fL --progress-bar -o "$ADAPTER_GGUF" \
        "https://huggingface.co/FinalRound/prepai-interviewer/resolve/main/interviewer-lora.gguf" \
        || { echo "ERROR: adapter download failed."; rm -f "$ADAPTER_GGUF"; exit 1; }
    fi

    # Register both tags. Paths are absolutised so `ollama create` resolves them
    # regardless of where it's invoked from.
    for spec in "$VLLM_BASE_MODEL:Modelfile.base" "$VLLM_MODEL:Modelfile.interviewer"; do
      tag="${spec%%:*}"; mf="ollama/${spec##*:}"
      if ollama list 2>/dev/null | grep -q "^${tag}[[:space:]]"; then
        echo "Ollama model '$tag' already registered — skipping."
      else
        echo "Registering Ollama model '$tag'..."
        sed "s|^ADAPTER \./models/|ADAPTER $(pwd)/ollama/models/|" "$mf" \
          | ollama create "$tag" -f - || { echo "ERROR: ollama create $tag failed."; exit 1; }
      fi
    done

    echo "Starting FinalRound with the local Qwen model via native Ollama (Metal)."
    $COMPOSE up -d --build
    ;;
  gemini)
    echo "Starting FinalRound in Gemini API mode (no local model services)."
    $COMPOSE up -d --build
    ;;
esac

# ── 5. Wait for the backend ──────────────────────────────────────────────────
printf "Waiting for the backend"
BACKEND_UP=""
for _ in $(seq 1 120); do
  if curl -sf http://localhost:8080/health >/dev/null 2>&1; then
    BACKEND_UP=1
    break
  fi
  printf .
  sleep 2
done
echo
if [ -z "$BACKEND_UP" ]; then
  echo "ERROR: backend did not come up within 4 minutes."
  echo "Check the logs: $COMPOSE logs backend"
  exit 1
fi
echo "Backend is up."

# ── 6. Seed the coding-problem bank (skipped when already populated) ─────────
COUNT=$($COMPOSE exec -T backend python -c "
import os, pymongo
c = pymongo.MongoClient(os.environ['MONGODB_URI'])
db = c[os.environ.get('DB_NAME', 'FinalRound')]
print(db[os.environ.get('PROBLEMS_COLLECTION', 'leetcode')].count_documents({}))
" 2>/dev/null | tr -d '[:space:]' || true)

if [ -n "$COUNT" ] && [ "$COUNT" -gt 0 ] 2>/dev/null; then
  echo "Problem bank already seeded ($COUNT problems) — skipping."
else
  echo "Seeding the coding-problem bank from LeetCode (one-time, a few minutes)..."
  $COMPOSE exec -T backend python -m scripts.scrape_leetcode --per-difficulty 25 --sleep 1.0
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo
echo "FinalRound is running:"
echo "  App:  http://localhost:3000"
echo "  API:  http://localhost:8080/docs"
if [ "$MODE" = "vllm" ]; then
  echo
  echo "Model: local Qwen2.5-7B via vLLM. The first interview may take 1-2 minutes"
  echo "to answer while the model loads; check progress with: $COMPOSE logs -f vllm"
elif [ "$MODE" = "ollama" ]; then
  echo
  echo "Model: local Qwen2.5-7B via native Ollama on Metal. The first interview"
  echo "may take a moment while the model loads into unified memory."
fi
